name: "Automatic Labeler"
description: 'Add automatic labels'
inputs:
  paths:
    description: 'Apply labels to events with mentions of these paths'
    required: false
    default: ''
  languages:
    description: 'Apply labels to events with mentions of these languages'
    required: false
    default: ''
  assign-self:
    description: 'Assign whoever triggers the pr to it'
    required: false
    default: ''
  github-token:
    description: 'Personal Access Token used for authentication'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.paths }}
    - ${{ inputs.languages }}
    - ${{ inputs.assign-self }}
    - ${{ inputs.github-token }}
