name: "Automatic Labeler"
description: 'Add automatic labels'
inputs:
  paths:
    description: 'Apply labels to events with mentions of these paths'
    required: false
    default: ''
  languages:
    description: 'Apply labels to events with mentions of these languages'
    required: false
    default: ''
  event:
    description: 'Event to apply labels to'
    required: true
  head:
    description: 'PR to checkout'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.paths }}
    - ${{ inputs.languages }}
    - ${{ inputs.event }}
    - ${{ inputs.head }}
