name: "Automatic PR Labeler"
on:
  pull_request:
    types: [opened]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changes
        id: detect
        uses: ./
        with:
          paths: |
            .: "root"
            Dockerfile: "docker"
            .github/workflows: "workflows"
          languages: |
            ts: "typescript"
            js: "javascript"
            tsx: "react"
            jsx: "react"
            yml: "config"
            yaml: "config"
            json: "config"
            md: "documentation"
            sh: "scripting"
          assign-self: 'true'
