name: "Automatic PR Labeler"
on:
  pull_request:
    types: [opened]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Detect changes
        id: detect
        run: |
          echo "Head_Ref: ${{ github.event.pull_request.head.sha }}"
          echo "Base_Ref: ${{ github.event.pull_request.base.sha }}"
          changes=($(git diff --name-only ${{ github.event.pull_request.head.sha }} ${{ github.event.pull_request.base.sha }}))
          echo "Changes: ${changes[@]}"